modelRoles:
  default: anthropic/claude-opus-5:xhigh

  fast_worker: opencode-go/deepseek-v4-flash:xhigh
  good_worker: opencode-go/deepseek-v4-flash:max

task:
  agentModelOverrides:
    sonic: "@fast_worker"
    task: "@good_worker"